= vim9-winswap
:doctype: article
:icons: font
:sectnums:
:toc:
//there's no need for a toc title in GitHub/HTML, but in PDF there is
ifndef::backend-html5,env-github[:toc-title: Contents]
ifdef::backend-html5,env-github[:toc-title:]

This Vim9 script plugin enables you to swap or clone Vim windows efficiently.
As a Vim9 script plugin, it works with Vim exclusively, and requires Vim
version 9 (though later versions of 8.2 may work too).

Vim&#x2019;s window built in `CTRL-W` commands, like `CTRL-W r`, `CTRL-W x`,
and `CTRL-W T`, work well in many scenarios.
However, there are limitations, which, depending on the
command, include resizing of windows and, for some commands,
e.g., `CTRL-W x`, sometimes mentally calculating the Nth window.
Also, there is no ability to move windows to another _existing_ tab.

What vim9-winswap enables is:

1. Swapping a chosen window with _any_ other, including a window in another
existing tab
2. Putting (cloning) a chosen window into _any_ other window, leaving the
&#x201C;yanked&#x201D; window as-is.
3. Using command, `:Winswap`, which will swap two specified windows.

In both instances:

* Local window options are carried across to the moved or cloned window.
That is, options like `list`, `colorcolumn`, and `spell`, which
are exclusively window-local.
* The state of the marked/&#x201C;yanked&#x201D; window is cleared
following a swap or put.

[NOTE]
====
Similar legacy plugin: https://github.com/wesQ3/vim-windowswap[vim-windowswap]
is a legacy vimscript plugin, which provides similar functionality for
swapping windows and the &#x201C;swap&#x201D; keys, `<Leader>ww`, have been
used for the _optional_ mappings.  There are improvements in Vim9-winswap,
though; e.g., vim-windowswap legacy plugin does not ensure local settings
are carried across, whereas in Vim9-winswap they are.
====

== Demonstrations

[TBC - Recording of examples, including showing swapping terminal, help
windows, multiple tabs, and so on.]

== How to swap windows

1. Navigate to the first window you want to swap
2. `<Leader>ww` to mark the window and remember its settings
3. Navigate to the second window you want to swap with the first
4. `<Leader>ww` to remember the second window's settings, then swap the windows

NOTE: `<Leader>ww` is not fixed - you can choose whatever you want - but it is
enabled if you used `g:winswap_opt_maps = true` in your (Vim9) .vimrc/_vimrc.

== How to put (clone) a window

1. Navigate to the window you want to put
2. `<Leader>ww` to mark the window and remember its settings
3. Navigate to the window you want to substitute
4. `<Leader>wp` to substitute the window with the cloned window from point 1

NOTE: `<Leader>wp` is not fixed - you can choose whatever you want - but it is
enabled if you used `g:winswap_opt_maps = true` in your (Vim9) .vimrc/_vimrc.

== How to swap windows by window number

If you know the window numbers of the two windows you want to swap, you can
use the `:Winswap` command:

[source,vim]
----
:Winswap 4 2
----

This will swap windows 4 and 2.  The command accepts any two valid
window numbers (though only within the same tab).

[NOTE]
====
For convenience, there is command abbreviation `Ws`, which expands
to `Winswap`.
====

== Mappings

=== Using `g:winswap_opt_maps`

If you are satisfied with using `<Leader>ww` and `<Leader>wp`, as explained
in <<_how_to_swap_windows>> and <<_how_to_put_clone_a_window>>, all you need
to do is to include the following in your .vimrc/_vimrc:

[source,vim]
----
g:winswap_opt_maps = true
----

=== `<Plug>` mappings and customising your mappings

There are only two inherent mappings, both of which work only in Normal mode.
They are `<Plug>` mappings, so they should not conflict with anything:

* `<Plug>(Winswap_ww)`
+
If there is no currently marked window, this marks it as the window that will
either be swapped or put/cloned.  If there already is a currently marked
window, it swaps the two windows.

* `<Plug>(Winswap_wp)`
+
Provided there is a currently marked window, this will put it (clone it to)
where the current window is.

If you want to map either or both of the `<Plug>` mappings to keys of your
own choosing, it is easy.  For example:

[source,vim]
----
nnoremap <C-W>2 <Plug>(Winswap_ww)
nnoremap <C-W>1 <Plug>(Winswap_wp)
----

Now `<C-W>2` will do the same as what `<Leader>ww` would do and `<C-W>1` will
do the same as what `<Leader>wp` would do.

== Installation

=== Using Vim&#x2019;s package management

From your terminal:

[source,bash]
----
git clone https://github.com/kennypete/vim9-winswap ~/.vim/pack/plugins/start/vim9-winswap
----

Adjust this as necessary for Windows and/or for `plugins`, which can be whatever
you want.  Also, if you want manual control of plugin loading, use `opt` instead
of `start`, then include `packadd vim9-winswap` in your .vimrc/_vimrc.

=== vim-plug

Add to your .vimrc/_vimrc, with your other
plugins, `Plug 'kennypete/vim9-winswap`.

== BSD Zero Clause License

Copyright &#xa9; 2025 Peter Kenny

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.

